apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatus
spec:
  replicas: 5
  selector:
    matchLabels:
      app: gatus
  template:
    metadata:
      labels:
        app: gatus
    spec:
      containers:
      - name: gatus
        image: twinproduction/gatus
        ports:
        - containerPort: 8080