---
- name: Converge
  hosts: all
  vars:
    runner_action: "install"
    runner_config_name: my_runner
    runner_config_labels: "linux,x-large"
    runner_config_token: 
  roles:
    - role: ansible-github-action-runner
