apiVersion: v1
kind: Service
metadata:
  name: nginx-service-clusterip
spec:
  selector:
    app: nginx-clusterip
  ports:
    - protocol: TCP
      port: 80       # Port exposed within the cluster
      targetPort: 80 # Port on the container
  type: ClusterIP   # Default type (ClusterIP)