apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-gp2
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  gcePersistentDisk:
    pdName: vol-0b810a052781b4d50
    fsType: ext4