apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
type: Opaque
data:
  username: bXl2ZXJ5c2VjcmV0dXNlcm5hbWUK      # base64 encoded value of 'my-username'
  password: dmVyeXZlcnlzZWNyZXRwYXNzd29yZAo=  # base64 encoded value of 'my-password'