name: 01.2 Prepare Docker VM with ansible

on:
  workflow_dispatch: 
    inputs:
      IP:
        type: string
        description: IP Address of the machine
        default:
      workdir:
        type: string
        description: Path to Ansible code
        default: 
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.event.inputs.workdir }}

    steps:
        - uses: actions/checkout@v4

        - name: Set up SSH key
          run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.AWS_EC2_SSH_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            # Optionally, add known hosts to avoid SSH prompts
            ssh-keyscan -H 35.158.140.211 >> ~/.ssh/known_hosts  # Replace with your VM's address
          

        - name: Prepare Docker VM with ansible
          run: ansible-playbook -u ubuntu -i inventory playbook.yml