name: 01.2 Prepare Docker VM with ansible

on:
  workflow_dispatch: 
    inputs:
      workdir:
        type: string
        description: Path to Ansible code
        default: 
jobs:
  build:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.event.inputs.workdir }}

    steps:
        - uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.x'

        - name: Install Ansible and Dependencies
          run: |
            python3 -m pip install ansible ansible-core boto3 botocore

        - name: Set up SSH key
          run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.AWS_EC2_SSH_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa          

        - name: Prepare Docker VM with ansible
          run: ansible-playbook -u ubuntu playbook.yml