name: Terraform Chekov

on:
  workflow_dispatch: 
    inputs:
      environment:
        type: string
        description: Path to Terraform code
        default: 50/terraform
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.event.inputs.environment }}

    steps:
      - uses: actions/checkout@v4 

      - name: Terraform plan
        id: terraform-plan
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan  
        run: terraform plan -out=tfplan

      - name: Terraform Chekov
        run: chekov -d ${{ github.event.inputs.environment }}

      - name: Terraform apply
        run: terraform apply -auto-approve tfplan