name: 01.4 Update Gatus Configuration

on:
  push:
    paths:
      - '54/config/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: 54/ansible

    steps:
        - uses: actions/checkout@v4

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v3
          with:
            role-to-assume: arn:aws:iam::034362059178:role/github-actions-role
            aws-region: eu-central-1

        - name: Set up SSH key
          run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.AWS_EC2_SSH_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa          

        - name: Prepare Docker VM with ansible
          run: ansible-playbook -u ubuntu -i inventory updateconfig.yml